//
//  YProtocol.swift
//  CRDTImplementation
//
//  Created by Lauri-Matti Parppei on 12.6.2026.
//

import yswift
import Foundation
import lib0
import Combine

import AppKit

public struct YUserAwareness:Codable {
    public var name:String
    public var userId:String
    public var location:Int
    public var length:Int
}

public enum YClientRole {
    case owner
    case editor
}

/**
 
 A basic text editor client implementation for `yswift`, a Swift port of Yjs.
 This is purpose-built to live on top of (beat), but might work for other applications as well.
 
 Unlike you are usually instructed to do, this implementation relies on __local echo__. macOS marked text weirdness gave me too much headache.
 
 */
@objc public class YClient:NSObject {
    
    public let doc:YDocument
    public let undoManager:YUndoManager
    public let origin = "local"
    public var room:String?
    
    /// Human-readable client name
    @objc public var clientName = "" {
        didSet {
            self.awareness.localState?.name = self.clientName
        }
    }
    
    /// Update hook for checking sync phases and doing something UI-related after sync
    public var onUpdate:((YSync.MessageType) -> Void)?
    /// Hook for room creation. We could maybe just use the above method.
    public var onRoomCreated:((String) -> Void)?
    /// Awareness data received
    public var onAwarenessUpdate:((YAwareness<YUserAwareness>) -> Void)?
    /// Called on disconnect. You get the plain disconnection message and the error if needed.
    public var onDisconnect:((YNetworkClientDisconnectReason, Error?) -> Void)?
    /// Another user joined the document
    public var onPeerJoined:((String, [String]) -> Void)?
    /// Another user left the document
    public var onPeerLeft:((String, [String]) -> Void)?
    /// This user successfully joined the room
    public var onJoinedRoom:((String) -> Void)?
    
    private var syncTask: Task<Void, Never>?
    
    var updateQueue:[Data] = []
    var updatesToMerge:[YUpdate] = []
    
    /// Network client for our CRDT client. This might allow other ways of connecting in the future, if needed.
    public var networkClient:YNetworkClient
    /// Returns `true` if the network client is currently connected.
    public var isConnected:Bool { return networkClient.isConnected }
    /// Returns `true` when a reconnect attempt is happening
    public var isReconnecting:Bool { return networkClient.isReconnecting }
    /// User ID is generated by the network client due to easier initialization.
    public var userId:String { return self.networkClient.userId }
    
    public var role:YClientRole = .owner
    
    private var syncCheckTimer:Timer?
    
    /// A list of local-first colors for
    private var userColors:[String:String] = [:]
    private let allColors:[String] = ["mint", "red", "green", "magenta", "blue", "yellow", "orange", "cyan"]
    private var nextUserColorIndex:Int = 0
    
    public let awareness:YAwareness = YAwareness<YUserAwareness>()
    private var objectBag = [AnyCancellable]()
    
    public init(doc: YDocument, server:String, clientName:String = "") {
        self.doc = doc
        self.clientName = clientName
        
        // We need to replace this hard-coded server name with something else at some point
        //self.networkClient = YNetworkClient(serverURL: URL(string: "ws://localhost:25110")!)
        self.networkClient = YNetworkClient(serverURL: URL(string: "ws://\(server)")!)
        self.undoManager = YUndoManager(doc.getText(), options: .make(captureTimeout: .infinity, trackedOrigins: YUndoManager.TrackOrigins(arrayLiteral: origin), document: doc))
        
        super.init()
        
        // User awareness
        self.setupAwareness()
        
        // Local update event
        doc.on(.init("update")) { [weak self] (args:(update: YUpdate, origin: Any?, txn: YTransaction)) in
            guard let self, self.networkClient.ready else { return }
            
            if let origin = args.origin as? String, origin == self.origin {
                self.sendUpdate(args.update)
            }
        }
        
        // Network events
        self.networkClient.onUpdates = { [weak self] messages in
            Task {
                await MainActor.run {
                    self?.receive(messages)
                }
            }
        }
        
        self.networkClient.onJoined = { [weak self] roomId in
            guard let self else { return }
            self.room = roomId
            
            // Post a sync message to let the other participant(s) know we're here.
            if self.role != .owner {
                self.sendSync(step: .step1)
            }
            
            // Sync heartbeat (checks for missing updates that might clog up the system)
            self.syncCheckTimer = createSyncCheckTimer()
            
            self.onJoinedRoom?(roomId)
        }
        
        self.networkClient.onRoomCreated = { [weak self] roomID in
            self?.room = roomID
            self?.onRoomCreated?(roomID)
            
            // Sync heartbeat (checks for missing updates that might clog up the system)
            self?.syncCheckTimer = self?.createSyncCheckTimer()
        }
        
        self.networkClient.onPeerJoined = { [weak self] member, allMembers in
            self?.onPeerJoined?(member, allMembers)
        }
        
        self.networkClient.onPeerLeft = { [weak self] member, allMembers, isHost in
            if let name = self?.userName(for: member) {
                NotificationCenter.default.post(name: .YPeerLeft, object: self, userInfo: ["name": name, "allMembers": allMembers])
            }
            self?.onPeerLeft?(member, allMembers)
        }
        
        self.networkClient.onDisconnected = { [weak self] reason, error in
            NotificationCenter.default.post(name: .YDisconnected, object: self, userInfo: ["reason": reason, "error": error])
            self?.syncCheckTimer?.invalidate()
            self?.syncCheckTimer = nil
            self?.onDisconnect?(reason, error)
        }
    }
    
    /// Creates a heartbeat for checking that the document is not missing any structs. If an update was lost on the way (due to network error or my silly programming bug), we'll send sync step 1 to get state vectors up to date.
    func createSyncCheckTimer() -> Timer {
        return Timer.scheduledTimer(withTimeInterval: 15.0, repeats: true, block: { [weak self] _ in
            guard let self else { return }
            
            if let pendingStructs = doc.store.pendingStructs, pendingStructs.missing.count > 0 {
                self.sendSync(step: .step1)
            }
        })
    }
    
    
    // MARK: - Teardown
    
    public func close() {
        // Invalidate pending tasks
        self.syncCheckTimer?.invalidate()
        self.syncCheckTimer = nil
        self.syncTask?.cancel()
        
        // Disconnect and destroy doc
        self.networkClient.disconnect()
        self.doc.destroy()
        self.awareness.unregister(self.doc)
        
        NotificationCenter.default.post(name: .YSessionEnded, object: self)
    }
    
    
    // MARK: - Awareness
    
    /// This is a list of pending user IDs that haven't been registered within awareness yet. Once they do, we'll post a notification of a new user.
    var pendingPeerNames: Set<String> = []
    
    /// Registers awareness object and sets up publisher for current document.
    func setupAwareness() {
        self.awareness.register(doc)
        self.awareness.updatePublisher.sink { [weak self] (update, origin) in
            guard let self, case .local = origin,
                  let update = self.awareness.encodeUpdate(of: update.changed.map{ $0 }) else {
                return
            }
            
            if let syncMessage = YSyncMessageWrapper(type: .awareness, data: update).asData() {
                addToQueue(syncMessage)
            }
            
            // Resolve any pending peer names
            for userId in pendingPeerNames {
                if let state = awareness.states.values.first(where: { $0.userId == userId }) {
                    let name = state.name
                    pendingPeerNames.remove(userId)
                    NotificationCenter.default.post(name: .YPeerJoined, object: self, userInfo: ["name": name])
                }
            }
        }
        .store(in: &objectBag)
        
        self.awareness.localState = YUserAwareness(name: self.clientName, userId: self.userId, location: 0, length: 0)
    }
    
    /// Returns the human-readable name for given user ID from awareness state
    public func userName(for userId:String) -> String? {
        if let state = awareness.states.values.first(where: { $0.userId == userId }) {
            return state.name
        } else {
            return nil
        }
    }
    
    /// Returns the color for given user ID. These colors are LOCAL and can't be defined by the end-user.
    @objc public func userColor(for userId:String) -> String {
        if let color = userColors[userId] {
            return color
        }
        
        let newColor = self.allColors[nextUserColorIndex % self.allColors.count]
        self.nextUserColorIndex += 1
        
        userColors[userId] = newColor
        
        return newColor
    }
    
    
    // MARK: - Connections
    
    /// Connect to a room. If string is `nil`, a new room will be created. You can either listen to `onRoomCreated` or access `.room` property to get the ID later.
    public func connect(room:String? = nil, onConnected:(() -> Void)? = nil)  {
        if onConnected != nil {
            self.networkClient.onConnected = onConnected
        }
        
        if room == nil {
            self.role = .owner
            self.networkClient.createRoom()
        } else if let room {
            self.role = .editor
            self.networkClient.joinRoom(room)
        }
    }
    
    public func reconnect() {
        guard let room else { print("No room available"); return }
        NotificationCenter.default.post(name: .YReconnecting, object: self)
        Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { [weak self] _ in
            self?.networkClient.reconnect(roomId: room)
        }
    }
    
    public func disconnect(onDisconnected:((YNetworkClientDisconnectReason, Error?) -> Void)? = nil) {
        if onDisconnected != nil {
            self.networkClient.onDisconnected = onDisconnected
        }
        self.networkClient.disconnect()
    }
    
    
    // MARK: - Sending updates
    
    func addToQueue(_ data:Data) {
        updateQueue.append(data)
        queueDidUpdate()
    }
    
    /// Send a single atomic update
    public func sendUpdate(_ update:YUpdate) {
        self.updatesToMerge.append(update)
        queueDidUpdate()
    }
    
    /// Send sync steps.
    /// - note Once the protocol receives step 1, step 2 is sent automatically.
    public func sendSync(step: YSync.MessageType) {
        guard let message = writeSync(step: step) else {
            print("Failed to write sync step")
            return
        }
        
        if let data = YSyncMessageWrapper(type: .sync, data: message).asData() {
            addToQueue(data)
        }
    }
    
    func queueDidUpdate() {
        syncTask?.cancel()
        syncTask = Task {
            try? await Task.sleep(nanoseconds: 100_000_000) // 0.1s
            guard !Task.isCancelled else { return }
            await MainActor.run {
                sendPendingUpdates()
            }
        }
    }
    
    private func sendPendingUpdates() {
        // Create a merged update of all queued updates.
        if !updatesToMerge.isEmpty,
           let mergedUpdate = try? YUpdate.merged(updatesToMerge),
           let message = writeUpdate(mergedUpdate) {
            // Append this single new update to queue as a normal wrapper message
            if let data = YSyncMessageWrapper(type: .update, data: message).asData() {
                updateQueue.append(data)
            }
        }
        
        // If the network client is not connected, we'll have to enqueue remaining updates
        if networkClient.ready {
            self.networkClient.sendUpdates(updateQueue)
            
            self.updateQueue.removeAll(keepingCapacity: true)
            self.updatesToMerge.removeAll(keepingCapacity: true)
        }
    }
    
    
    // MARK: - Receiving and reading updates
    
    /// Handles incoming messages. Add `onUpdate` listener for handling them.
    func receive(_ messages:[Data]) {
        for message in messages {
            if let syncMessage = try? JSONDecoder().decode(YSyncMessageWrapper.self, from: message) {
                if syncMessage.type == .update || syncMessage.type == .sync {
                    if let messageType = readUpdate(syncMessage.data) {
                        // The update has now been applied and we'll still tell the client observer what happed
                        onUpdate?(messageType)
                    }
                } else if syncMessage.type == .awareness {
                    readAwareness(syncMessage.data)
                }
            }
        }
    }
    
    /// Applies binary updates to YDocument. Don't use this directly.
    private func readUpdate(_ message:Data) -> YSync.MessageType? {
        do {
            let decoder = LZDecoder(message)
            let encoder = LZEncoder()
            var messageType:YSync.MessageType? = nil
            
            messageType = try YSync.readSyncMessage(decoder: decoder, encoder: encoder, doc: self.doc)
            
            if let messageType {
                if messageType == .step1 {
                    // Upon receiving step 1, we'll immediately send step 2
                    sendSync(step: .step2)
                }
            }
            
            return messageType
            
        } catch {
            print("ERROR: Can't read sync message: ", message)
            return nil
        }
    }
    
    private func readAwareness(_ message:Data) {
        self.awareness.applyUpdate(message, origin: .custom("remote"))
        Task { [weak self] in
            await MainActor.run {
                guard let self else { return }
                self.onAwarenessUpdate?(self.awareness)
            }
        }
    }
    
    public func activeUsers() -> [YUserAwareness] {
        let users = awareness.states.values.compactMap {
            // Only include online users and our local presence
            return (networkClient.activePeers.contains($0.userId) || $0.userId == self.userId) ? $0 : nil
        }
        
        return users
    }
    
    
    // MARK: - Writing updates
    
    /// Creates a binary message from a single update. Use `sendUpdate` to automatically create and send the update.
    private func writeUpdate(_ update:YUpdate) -> Data? {
        let encoder = LZEncoder()
        YSync.writeUpdate(encoder: encoder, update: update)
        
        return encoder.data
    }
    
    /// Creates sync step. Use `sendSync` to automatically create and send a sync step.
    private func writeSync(step: YSync.MessageType) -> Data? {
        let encoder = LZEncoder()
        do {
            if step == .step1 {
                try YSync.writeSyncStep1(encoder: encoder, doc: self.doc)
            } else if step == .step2 {
                try YSync.writeSyncStep2(encoder: encoder, doc: self.doc, encodedStateVector: nil)
            }
            
            return encoder.data
        } catch {
            print("ERROR: Failed to create sync step")
            return nil
        }
    }
    
    /// Updates local selection
    public func updateSelectedRange(_ range:NSRange) {
        guard let awareness = self.awareness.localState else { return }
        if awareness.location == range.location && awareness.length == range.length {
            return
        }
        
        self.awareness.localState?.location = range.location
        self.awareness.localState?.length = range.length
    }
    
    
    // MARK: - Text view setup
    
    public var textObserver:((YEvent, YTransaction) -> Void)? {
        didSet {
            self.doc.getText().observe { [weak self] event, txn in
                self?.textObserver?(event, txn)
            }
        }
    }
    
    
    // MARK: - Local text edits
    
    @objc public func applyLocalEdit(editedRange:NSRange, delta:Int, textStorage:NSTextStorage) {
        let loc = editedRange.location
        let added = editedRange.length
        let deleted = editedRange.length - delta
        
        let string = (textStorage.string as NSString).substring(with: editedRange)
        let text = doc.getText()
        doc.transact(origin: self.origin) { txn in
            if deleted > 0 {
                text.delete(loc, length: deleted)
            }
            
            if added > 0 {
                text.insert(loc, text: string)
            }
        }
    }
    
}


extension YClient {
    
    // MARK: - Undo / redo
    
    @objc public func canUndo() -> Bool {
        return self.undoManager.canUndo()
    }
    
    @objc public func canRedo() -> Bool {
        return self.undoManager.canRedo()
    }
    
    @objc public func undo() {
        self.undoManager.undo()
    }
    
    @objc public func redo() {
        self.undoManager.redo()
    }
    
    @objc public func isUndoing() -> Bool {
        return self.undoManager.undoing
    }
    
    @objc public func isRedoing() -> Bool {
        return self.undoManager.redoing
    }
    
}


extension YClient {
    
    // MARK: - Attributes
    
    public func addSharedAttribute(key:NSAttributedString.Key, value:Any, range:NSRange) {
        if let value = value as? YTextAttributeValue {
            doc.transact(origin: self.origin) {
                let text = doc.getText()
                text.addAttribute(key.rawValue, value: value, range: range)
            }
        }
    }
    
    public func removeSharedAttribute(key:NSAttributedString.Key, range:NSRange) {
        doc.transact(origin: self.origin) {
            let text = doc.getText()
            text.removeAttribute(key.rawValue, range: range)
        }
    }
}


// MARK: - Notification names

public extension Notification.Name {
    public static let YPeerJoined   = Notification.Name("peerJoined")
    public static let YPeerLeft     = Notification.Name("peerLeft")
    public static let YHostLeft     = Notification.Name("hostLeft")
    public static let YDisconnected = Notification.Name("disconnected")
    public static let YSessionEnded = Notification.Name("sessionEnded")
    public static let YReconnecting = Notification.Name("reconnecting")
}
